### ISSUE TITLE
Face extractor suddenly not working

### ISSUE THREAD

**Issue by Mjolnir343** [iperov/DeepFaceLab#138]
I have been using this tool for weeks now with great success. Today however, I went to start a new project and when I tried to extract faces I get this:

Running extractor.

Performing 1st pass...
Running on GeForce RTX 2080 Ti #0.
Running on GeForce RTX 2080 Ti #1.
Running on GeForce RTX 2080 Ti #2.
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #3.
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #4.
2019-02-08 15:38:14.741749: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #0.
2019-02-08 15:38:15.014292: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-08 15:38:15.115065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:15.121131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #1.
2019-02-08 15:38:15.287669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:15.294814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-08 15:38:15.353547: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #2.
2019-02-08 15:38:15.604280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:15.611058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-08 15:38:15.624493: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #3.
2019-02-08 15:38:15.905067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:15.912089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-08 15:38:16.029072: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-08 15:38:16.090602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:16.095060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-08 15:38:16.097445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-08 15:38:16.100614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Running on GeForce RTX 2080 Ti #4.
2019-02-08 15:38:16.260437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:16.264826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-08 15:38:16.267262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-08 15:38:16.270518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:16.325476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:16.332506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-08 15:38:16.384280: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-02-08 15:38:16.606718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:16.610345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-08 15:38:16.612592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-08 15:38:16.615231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:16.706227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:16.712882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:142019-02-08 15:38:16.9701] 4Adding visibl9e gpu de61: vices: 1
I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
L:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-02-08 15:38:16.908849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:16.913223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-08 15:38:16.915737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-08 15:38:16.918248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:17.044335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:17.052091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 1
2019-02-08 15:38:17.147948: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-08 15:38:17.306886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExeL:\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
cutor with strength 1 edge matrix:
2019-02-08 15:38:17.311782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-08 15:38:17.314093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-08 15:38:17.317167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:17.463519: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-08 15:38:17.526144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:17.533430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 1
2019-02-08 15:38:17.728667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:17.732775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      1
2019-02-08 15:38:17.734967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N
2019-02-08 15:38:17.738198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:17.820152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:17.827656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 1
2019-02-08 15:38:17.899698: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-08 15:38:18.100872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:18.105234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      1
2019-02-08 15:38:18.107628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N
2019-02-08 15:38:18.110115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:18.292044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 8.95GiB
2019-02-08 15:38:18.299400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 1
2019-02-08 15:38:18.655687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:18.659638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      1
2019-02-08 15:38:18.661978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N
2019-02-08 15:38:18.665248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:18.951069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:18.955278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      1
2019-02-08 15:38:18.957545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N
2019-02-08 15:38:18.961388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Using TensorFlow backend.
2019-02-08 15:38:19.365762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-08 15:38:19.370262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      1
2019-02-08 15:38:19.372723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 1:   N
2019-02-08 15:38:19.376074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8632 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Using TensorFlow backend.
 15%|###########5                                                                  | 1052/7096 [01:46<08:34, 11.75it/s]2019-02-08 15:40:12.199814: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.00G (1073741824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-02-08 15:40:12.205835: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 921.60M (966367744 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-02-08 15:40:12.212414: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 829.44M (869731072 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-02-08 15:40:12.239659: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.00G (1073741824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
 15%|###########9                                                                  | 1088/7096 [01:50<18:36,  5.38it/s]2019-02-08 15:40:18.808938: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
 15%|###########9                                                                  | 1090/7096 [01:52<55:06,  1.82it/s]2010199--02-08 15:40:18.8240726-7: E tensorflow/stream_ex08e 15:cutor/cuda/cuda_4timer.c0c::5 15%|###########9                                                                  | 1091/7096 [01:53<55:55,  1.79it/s]] fail1D29C4ed to sy95A70: CUDAnchronize_ERROR_LAUNCH_ the stoTIMEOUT: thep even launch tt: CUDA_ERROiR_meLAUNCH_FAId LEDout and wa: unspecified launs terminatech fda
i2019-lure
02201-08 15:40:19.4309-02131:-08 15:40 E: t19.430803: E tensorflensoow/stream_executorflow/stream_executor/cuda/cuda_timer.crc:60/c] Internaul:d earro/r decsturoyidnga C_UDA evetnti merin .cocnct:e5x5]t 00 Inter0na00l:1 eDrror des29C49t5Aroying CUD70: A eventCUDA_E RiRnO cRo_nLtAeUxNtC H0_TIMEOUT:000 0t1AhFe9 lAaDu3nc5h3 Ct0i:m eCdU DoAu_tE aRnd was terminated
ROR_LAUNCH_FAILED: unspecified launch failure
22019019--0022--08 15:40:19.4540818:8 1 E 5:40tensor:flow/s19.tre453015: F tensoram_executoflow/stream_executor/cuda/cuda_rd/cuda/cnuda_timn.ecr.cc:6c0:21] Int1ernal: erro] Checr deks failedt: stroyiatus n== g CCUUDA DNeN_STvenATt inUS_SUCCESS (7 vs cont.ext 00 0)F0001AFa9ileAd to D35set3C0: cuDNN st rCeUamD.
A_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:19.471848: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
 16%|############1                                                                 | 1106/7096 [01:57<33:54,  2.94it/s]2019-02-08 15:40:24.711426: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.00G (1073741824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-02-08 15:40:24.716675: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 835.08MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-02-08 15:40:24.749709: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 1.00G (1073741824 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-02-08 15:40:24.754466: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 835.08MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
 16%|############2                                                                 | 1110/7096 [01:59<47:12,  2.11it/s]2019-02-08 15:40:25.779298: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:25.784090: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 00000270510E29F0: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:25.805472: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 00000270510E29F0: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:25.844950: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
 16%|############2                                                                 | 1111/7096 [02:00<39:58,  2.49it/s]2019-02-08 15:40:25.978389: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:25.992880: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 000001F519CC9D10: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:25.997843: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 000001F519CC9D10: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:26.012519: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
 17%|#############2                                                                | 1208/7096 [02:10<33:03,  2.97it/s]2019-02-08 15:40:36.960975: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:36.965626: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 000001E28713F3C0: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:36.978148: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 000001E28713F3C0: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-02-08 15:40:36.985740: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
 17%|#############2                                                                | 1209/7096 [02:11<28:45,  3.41it/s]2019-02-08 15:40:37.071285: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:37.075514: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 0000019599430180: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:37.081448: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 0000019599430180: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-02-08 15:40:37.086713: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
 21%|################3                                                             | 1489/7096 [02:48<12:19,  7.58it/s]GeForce RTX 2080 Ti #1 doesnt response, terminating it.
 21%|################4                                                             | 1494/7096 [02:49<13:29,  6.92it/s]GeForce RTX 2080 Ti #4 doesnt response, terminating it.
 22%|#################                                                             | 1552/7096 [02:56<14:35,  6.33it/s]GeForce RTX 2080 Ti #3 doesnt response, terminating it.
 22%|#################                                                             | 1554/7096 [02:57<15:14,  6.06it/s]GeForce RTX 2080 Ti #2 doesnt response, terminating it.
 23%|##################                                                            | 1646/7096 [03:07<11:11,  8.12it/s]GeForce RTX 2080 Ti #1 doesnt response, terminating it.
 23%|##################1                                                           | 1649/7096 [03:08<10:57,  8.29it/s]GeForce RTX 2080 Ti #4 doesnt response, terminating it.
 26%|####################                                                          | 1827/7096 [03:29<13:57,  6.29it/s]

The extractor will run for a bit with varying degrees of success, but it's very slow and eventually crashes the display. Running on just one card increases the odds of success, but it's still very slow. It seems like it's asking for too much memory, but I only have a cursory knowledge of how arcane computer magic actually works, so I'm just guessing. I've read that the RTX cards are currently having TensorFlow issues, but everything has worked fine until now.

The only thing I can think of that's changed is that I moved to a new apartment. I checked all the physical connections of my computer, i.e. cards, wires, memory, etc., but everything is nicely seated. Games and movies and general computing work just fine.

Here's a pastebin of my DxDiag: https://pastebin.com/EBQnePaE

Thanks in advance for any assistance.

**Comment by wanshun123** [comment]
Issue with RTX cards https://github.com/iperov/DeepFaceLab/issues/130

**Comment by Mjolnir343** [comment]
Why was it working so well for so long? Did I just luck out?

**Comment by wanshun123** [comment]
I have no idea - I thought it was always the case that RTX cards don't run face extraction with this software. Hopefully someone else can comment.

**Comment by iperov** [comment]
i have no RTX 2080 TI , cannot say anything. 
I am planning to support RTX when tf 1.13 (not rc) will be released

**Comment by gessyoo** [comment]
@Mjolnir343, just to clarify, you were able to extract with your rig before you moved to a new apartment, and now extract doesn't work?  Did you download a newer build of DFL or upgrade your video driver?  If all physical connections are OK (GPUs or power connectors have been jostled slightly in the move), then check your disk drive for errors.

**Comment by Mjolnir343** [comment]
@gessyoo, correct. Everything was fine before the move. I've made several SNL deepfake videos for the r/GifFakes subreddit, and they turned out very nicely. I haven't had a single odd message or error in the couple of months I've been playing with the tool.

I checked all the physical connections visually. I have a rigid tubing LCS setup, so I didn't re-seat either of the cards. My drives are M.2 SSDs, so they should have weathered any rough handling, but I'll run some diagnostics anyways. They're held in place with a screw and under a heatsink, so I didn't check them visually.

I've since run a bunch of benchmarks and even reinstalled Windows, but it still isn't working. My computer was offline for about a week during the move, so there were definitely some driver updates in Nvidia GeForce Experience when I got everything set back up at the new place. 

At this point, it looks like new drivers popped whatever bubble of stability I was in. I've never tried to roll back drivers before, but it doesn't look very difficult. I'll try that next.

**Comment by Mjolnir343** [comment]
Well, rolling back the GPU drivers to their previous state didn't change a thing. I guess I'm just gonna have to be patient and hope that tensorflow 1.13 fixes the problem, whatever the problem is.

**Comment by Mjolnir343** [comment]
Question: I ran the MT extractor with the --cpu-only argument, but it still throws a mess of errors and crashes by the 2nd pass. If my issue is a RTX/CUDA 10 issue, why doesn't the CPU only extractor work?

**Comment by gessyoo** [comment]
@Mjolnir343, the DeepFaceLab torrent has a separate CPU installation for CPU-only, look for a file named"DeepFaceLabCPUTorrent ---. Zip" in the torrent download location.

**Comment by Mjolnir343** [comment]
@gessyoo, Roger that. Thanks for the heads up.

**Comment by wanshun123** [comment]
I just tried running `4) data_src extract faces MT best GPU.bat` on my machine (on the default data_src video) with an RTX 2080 for the first time and surprisingly it worked:

```
Running extractor.

Performing 1st pass...
Running on GeForce RTX 2080 #0.
Running on GeForce RTX 2080 #1.
Running on GeForce RTX 2080 #2.
Running on GeForce RTX 2080 #3.
X:\python\DF\DFL\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
X:\python\DF\DFL\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
X:\python\DF\DFL\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
X:\python\DF\DFL\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-02-18 15:41:36.550938: 20I tensorflow/core/platform/cpu_feat1ure_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
9-02-18 15:41:36.553530: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-18 15:41:36.552267: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-18 15:42019-02-18 15:41:37.080831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
n2019-02-18 15:41:37.102491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.53GiB
ame: GeForce RTX 2080 majo2019-02-18 15:41:37.154420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
r: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.53GiB
2019-02-182019-02-18 15:41:37.284867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.51GiB
2019-02-18 15:41:37.348345:1 15:41:37.28151 I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
5: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
:36.553642: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-18 15:41:39.073803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.40GiB
2019-02-18 15:41:39.079393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-18 15:45:56.160704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-18 15:45:56.163449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9772019-022]-18 15:45:56.0      0
245498: I tensorflow/core/common_runtime2019-02-18 1/gp19-02-18 15:45:565:45:56.25.7855: I tenso217530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-18 15:45:56.271552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-18 15:45:56.277322: I tensorflow/core/comru/gpu_device.cc:971] Device interconnect Sflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
treamExecutor with strength 1 edge mamon_runtime/gpu/gpu_device.cc:trix:
2019-02-18 15:45:56.290791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-18 15:45:56.299623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
990] 0:   N
2019-02-18 15:45:56.326888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5882 MB memory) -> physical GPU (device: 0, name: Ge22019-02-18 15:45:56.01327100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:Force RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
9-02-18 15:45:56.327032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] 1Created 103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5882 MB memory) -> physiTensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5882 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute ccal GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:apability: 7.5)
01:00.0, compute capability: 7.5)
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
2019-02-18 15:46:08.463249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-18 15:46:08.471462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-18 15:46:08.476718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-18 15:46:08.482973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5730 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
100%|################################################################################| 655/655 [07:37<00:00,  1.43it/s]
Performing 2nd pass...
Running on GeForce RTX 2080.
X:\python\DF\DFL\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-02-18 15:54:51.138304: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-18 15:54:57.355904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.53GiB
2019-02-18 15:54:57.372596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-18 15:55:05.680607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-18 15:55:05.692169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-18 15:55:05.717492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-18 15:55:05.745785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6270 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
100%|################################################################################| 655/655 [01:18<00:00,  8.29it/s]
Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
100%|################################################################################| 655/655 [00:09<00:00, 69.74it/s]
-------------------------
Images found:        655
Faces detected:      654
-------------------------
Done.
Press any key to continue . . .
```

I'm using Cuda 9.2, nvidia driver 411.70.

**Comment by DuyTheDao** [comment]
@wanshun123  same here, did it with my 2070 and it worked.
