### ISSUE TITLE
Tesla GPU does not work on tf 1.13.1 / CUDA 10

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#175]
Get this when trying base settings. Just downloaded the Windows App, latest ver.

 Model options:
|== batch_size : 4
|== sort_by_yaw : False
|== random_flip : True
|== resolution : 128
|== face_type : f
|== learn_mask : True
|== archi : df
|== ae_dims : 512
|== ed_ch_dims : 42
|== lighter_encoder : False
|== multiscale_decoder : True
|== pixel_loss : False
|== face_style_power : 0.0
|== bg_style_power : 0.0
Running on:
|== [0 : Tesla V100-SXM2-32GB]
=========================
Saving...
Starting. Press "Enter" to stop training and save model.
2019-02-28 15:24:17.061889: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
2019-02-28 15:24:19.501210: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.524294: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.537892: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.550181: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.560771: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.572558: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.583995: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.597609: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.612175: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.623017: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.634949: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.646698: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.659910: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.672570: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.684968: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-28 15:24:19.695337: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node truediv_1}}]]
         [[{{node Mean_6}}]]
Traceback (most recent call last):

  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\mainscripts\Trainer.py", line 75, in trainerThread
    loss_string = model.train_one_epoch()
  File "C:\Users\peterDownloads\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\models\ModelBase.py", line 309, in train_one_epoch
    losses = self.onTrainOneEpoch(sample, self.generator_list)
  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\models\Model_SAE\Model.py", line 385, in onTrainOneEpoch
    src_loss, dst_loss, = self.src_dst_train (feed)
  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\peter\Downloads\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node truediv_1}}]]
         [[{{node Mean_6}}]]
Done.

**Comment by iperov** [comment]
did you update card drivers?

**Comment by Tesla32X** [comment]
Yeah, driver is just a few days old. I will try a reinstall with clean install

**Comment by iperov** [comment]
give me teamviewer access I will check , send to deepfakescovery@gmail.com

**Comment by iperov** [comment]
hello?

**Comment by Tesla32X** [comment]
I have two different rigs, and wanted to give it a shot on the second machine. Same error on Tesla 16 GB version. I will send you email with access to it.

**Comment by iperov** [comment]
wait new release, I need you to test it.

**Comment by iperov** [comment]
1 hour

**Comment by Tesla32X** [comment]
Ok, I will check back then

**Comment by iperov** [comment]
sorry, but I cannot downgrade to tf 1.12 because it uses CUDA 9.
RTX cards requires CUDA 10.

Therefore use previous version and manually update deepfacelab folder.

We will wait new tf 1.13.x releases , may be they will fix problems,

**Comment by Tesla32X** [comment]
ok, thx for trying. What  version should I go back to?

**Comment by iperov** [comment]
https://mega.nz/fm/ykMF1CDA 25-02

**Comment by Tesla32X** [comment]
👍 Thx!

**Comment by iperov** [comment]
also did you try to reboot pc?
this man got similar error, but reboot help him
https://mrdeepfakes.com/forums/thread-deepfacelab-explained-and-usage-tutorial?pid=3663#pid3663

**Comment by Tesla32X** [comment]
Just tested the "Tesla OK" version and still got error. I have done several reboots, so I doubt that is the issue. I also tried installing some older Nvidia drivers with no luck.

2019-03-02 20:10:53.427453: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.500905: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.516649: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.523953: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.530697: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.539919: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.546318: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-02 20:10:53.555229: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

**Comment by iperov** [comment]
then I dont know how to fix your problem.

02.25 build on old CUDA 9 version.

**Comment by dream80** [comment]
I use Tesla K80 without problems
DFL 2-25 version
Runing on Google Cloud  Platform  Compute Engine

**Comment by iperov** [comment]
@dream80 is Tesla work on last version ?

**Comment by dream80** [comment]
2.25 version
I can test the latest version later

**Comment by dream80** [comment]
Running on Tesla K80

**Operating system Window Server 2016**
**The driver is 386.45-tesla-desktop-win10-64bit-international**
DeepFaceLabCUDA_build_25_02_2019 This version is good
DeepFaceLabCUDA_build_03_01_2019 RTX OK This version gives an error when extracting!

**After updating the driver**

**Operating system Window Server 2016**
**The driver is 412.29-tesla-desktop-win10-64bit-international**
DeepFaceLabCUDA_build_25_02_2019 This version is good
DeepFaceLabCUDA_build_03_01_2019 RTX OK This version is good

Driver download address: https://www.nvidia.cn/Download/index.aspx?lang=cn
![qq 20190303173220](https://user-images.githubusercontent.com/20279174/53693358-546b6500-3dda-11e9-9855-7958a801f1ae.jpg)

**Comment by iperov** [comment]
@dream80 thank you very much for testing

**Comment by dream80** [comment]
You are welcome ， DFL is great，Easy to use！

**Comment by 94leon** [comment]
My new  cloud service used Tesla P4 has the same problem, and the 25-02 version also cannot run, is this software not compatible?Should I change to another GPU？

**Comment by 94leon** [comment]
> Just tested the "Tesla OK" version and still got error. I have done several reboots, so I doubt that is the issue. I also tried installing some older Nvidia drivers with no luck.
> 
> 2019-03-02 20:10:53.427453: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.500905: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.516649: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.523953: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.530697: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.539919: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.546318: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.555229: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

你的问题解决了吗，我的P4云服务器也遇到了同样的问题，求教

**Comment by 94leon** [comment]
> Just tested the "Tesla OK" version and still got error. I have done several reboots, so I doubt that is the issue. I also tried installing some older Nvidia drivers with no luck.
> 
> 2019-03-02 20:10:53.427453: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.500905: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.516649: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.523953: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.530697: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.539919: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.546318: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2019-03-02 20:10:53.555229: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

Have you solved your problem? My P4 GPU cloud server has also encountered the same problem，Can you give me some guidance?

**Comment by iperov** [comment]
@94leon post info cmd - ver

**Comment by oracle9i88** [comment]
my p4 also cannot work. 
Using TensorFlow backend.
Loading: 0it [00:00, ?it/s]
Loading: 100%|#################################| 19/19 [00:00<00:00, 324.11it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/root/DeepFaceLab_Linux/mainscripts/Trainer.py", line 41, in trainerThread
    device_args=device_args)
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 154, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/samples/SampleGeneratorFace.py", line 57, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.

ubuntu 16.04 cuda90 cudnn7.1.4

and the data_dst is using cpu-only made

**Comment by iperov** [comment]
I dont support ubuntu

**Comment by oracle9i88** [comment]
wuwu...crying..

**Comment by iperov** [comment]
Loading: 0it [00:00, ?it/s] - no samples

**Comment by oracle9i88** [comment]
but there are lots of

**Comment by iperov** [comment]
as you wish

**Comment by oracle9i88** [comment]
oh, the data_dst/aligned is full...wuwu..crying

**Comment by iperov** [comment]
and src?

**Comment by oracle9i88** [comment]
Loading: 100%|#################################| 10/10 [00:00<00:00, 160.40it/s]
Loading: 100%|#################################| 19/19 [00:00<00:00, 565.02it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/root/DeepFaceLab_Linux/mainscripts/Trainer.py", line 41, in trainerThread
    device_args=device_args)
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 154, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/models/ModelBase.py", line 306, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/root/DeepFaceLab_Linux/samples/SampleGeneratorFace.py", line 57, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.
(deepface) root@ubuntu:~/DeepFaceLab_Linux# 
(deepface) root@ubuntu:~/DeepFaceLab_Linux#

**Comment by oracle9i88** [comment]
dst 10
src 19
all find

**Comment by iperov** [comment]
add more samples

**Comment by iperov** [comment]
hm no, stop flood at this topic

**Comment by Tesla32X** [comment]
Not sure what happened. Have been running this app on google cloud service with various cards. Had zero issues.

But recently these errors occured. Can’t get the 25.02 version to run either.

**Comment by iperov** [comment]
try last builds

**Comment by humaolin** [comment]
https://github.com/inoryy/tensorflow-optimized-wheels/releases/download/v2.0.0a0/tensorflow-2.0.0a0-cp37-cp37m-linux_x86_64.whl

I use this whl solved my problem
