### ISSUE TITLE
CUDA9.2SSE  cudnn has crash

### ISSUE THREAD

**Issue by deyu260** [iperov/DeepFaceLab#193]
DeepFaceLabCUDA9.2SSE_build_03_11_2019 has carsh，error log say: Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR，I installed the driver correctly and cuda and cudnn。

cuda_9.2.148_win10
cudnn-9.2-windows10-x64-v7.4.2.24

os windows 10 2019 ltsc
cpu amd x830 
motherboard GA 780G Integrated Graphics HD3200
memory 2Gx8
Graphics card p106 6g

//===== Model summary =====
//== Model name: H128
//==
//== Current epoch: 0
//==
//== Model options:
//== |== batch_size : 4
//== |== sort_by_yaw : False
//== |== random_flip : True
//== |== lighter_ae : False
//== |== pixel_loss : False
//== Running on:
//== |== [0 : P106-100]
//=========================
Saving...
Starting. Press "Enter" to stop training and save model.
2019-03-15 19:42:35.937782: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-15 19:42:35.943660: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-15 19:42:35.950721: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-15 19:42:35.955916: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node model_1_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_45"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/model_1_1/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node loss/model_2_loss_1/Mean_3/_567}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4729_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 75, in trainerThread
    loss_string = model.train_one_epoch()
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 309, in train_one_epoch
    losses = self.onTrainOneEpoch(sample, self.generator_list)
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_H128\Model.py", line 84, in onTrainOneEpoch
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_mask, warped_dst, target_dst_mask], [target_src, target_src_mask, target_dst, target_dst_mask] )
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\temp\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node model_1_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_45"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/model_1_1/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node loss/model_2_loss_1/Mean_3/_567}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4729_loss/model_2_loss_1/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Done.
请按任意键继续. . .

**Comment by iperov** [comment]
You should not to install cuda or cudnn.

**Comment by iperov** [comment]
and try to reboot pc

**Comment by deyu260** [comment]
I only installed cuda and cudnn after cudnn went wrong. 
I did not solve the problem after rebooting

**Comment by iperov** [comment]
where you find that you have to install cuda and cudnn?

**Comment by iperov** [comment]
uninstall cuda
uninstall cudnn
perform CLEAN INSTALL driver from GEFORCE.COM

**Comment by deyu260** [comment]
I installed the latest driver containing cuda10.dll or the legacy driver of cuda9.dll. Which one should I install?

**Comment by iperov** [comment]
You must not to install cuda or cudnn.

**Comment by iperov** [comment]
get help in your QQ groups

**Comment by deyu260** [comment]
418.91-desktop-win10-64bit-international-whql is work。QQ群里的提问扯淡2小时，自己百度5分钟。

**Comment by CZOY08** [comment]
Same issue here with the recent pre-builds, runing on windows10 p106-100 without cuda installed, nether 418.91 or 419.69 works for me. @deyu260 和你同款显卡， 418.91 和 419.69试过都不行，没有安装cuda，运行最近的build都提示和你相同的错误，请问你具体是怎么解决的？

**Comment by deyu260** [comment]
@CZOY08  我用的是3月13号的sse版本，一切都没问题，确保你的驱动卸载干净了，断网安装418.91-desktop-win10-64bit-international-whql，有必要甚至重装系统，或者换linux，兼容性是做好的

**Comment by CZOY08** [comment]
@deyu260 我试了一下3月13号的sse版本，也是一切正常，但是3月26和3月31的sse我的都提示那个错误。于是我是了一下LINUX的最新版，之前是3月15左右配置的，一切正常，git更新到最新版本，运行提示和windows上一样的错误。你有时间的话能试下新的prebuilt吗，我不完全确定是我这边配置的问题还是p106兼容性的问题

**Comment by CZOY08** [comment]
![Screenshot from 2019-04-03 11-00-03](https://user-images.githubusercontent.com/47473411/55450385-7d615e80-5601-11e9-8170-608c4000f6e0.png)

**Comment by deyu260** [comment]
@CZOY08  你都说了用的3月13号正常，换之后的版本就有问题了，我觉得这不单单是环境的问题了。作者也不接受这类环境问题反馈了，你还不如把新版本变动的文件拿到老版本上用了。
