### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by jveryl** [iperov/DeepFaceLab#369]
My GPU  is RTX2080 SUPER,

DeepFaceLabCUDA10.1AVX
I execute the [ 6) train H128 ],
                     ↓
---------------------------------------------------
Starting. Press "Enter" to stop training and save model.
2019-08-24 01:11:32.333585: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.12G (2279250176 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by Obsyden** [comment]
Try lowering the batch size, i.e start from 4 and double until you get the error. 

If this doesn't work, changing line 144 in `nnlib.py` to `config.gpu_options.allow_growth = False` seemed to stop this error appearing for me.

**Comment by jveryl** [comment]
> 尝试降低批量大小，即从4开始并加倍，直到出现错误。
> 
> 如果这不起作用，改变线144 `nnlib.py`到`config.gpu_options.allow_growth = False`似乎停止出现了我这个错误。

-----------------------
Thank u! :)

**Comment by sldev14** [comment]
Thank!. It helped!
