### ISSUE TITLE
The trainer does not work in the DeepFaceLab_CUDA_9.2_SSE, both the face extractions work well.

### ISSUE THREAD

**Issue by jiujitsu101** [iperov/DeepFaceLab#538]
**Hi,
The DeepFaceLab work in all things except for training on my laptop. 
I am using:
I7-8th gen
NVIDIA Geforce GTX 1050Ti - 4 GB VRAM
CUDA 10.0 (Installed just for being safe)
cuDNN related to it also installed
installed latest tensorflow

The face extractions work well. Faces are extracted with no problem at all. The problem is during training. I click on the train H64 option and select all the default option (just pressing enter).
Then the program loads for a few seconds and then burn out showing the message;**
"
Starting. Press "Enter" to stop training and save model.
[14:55:00][#000001][9578ms][3.8497][2.0770]
Error: OOM when allocating tensor with shape[2048,1024,3,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/gradients/model_1/conv2d_5/convolution_grad/Conv2DBackpropFilter}} = Conv2DBackpropFilter[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/model_1/conv2d_5/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, ConstantFolding/training/Adam/gradients/model_1/conv2d_5/convolution_grad/ShapeN-matshapes-1, training/Adam/gradients/AddN_23)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 109, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 506, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 88, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\x\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2048,1024,3,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/gradients/model_1/conv2d_5/convolution_grad/Conv2DBackpropFilter}} = Conv2DBackpropFilter[T=DT_FLOAT, _class=["loc:@train...kpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/model_1/conv2d_5/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, ConstantFolding/training/Adam/gradients/model_1/conv2d_5/convolution_grad/ShapeN-matshapes-1, training/Adam/gradients/AddN_23)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.
Press any key to continue . . .
"

Please sir help if you can, I have downloaded all sorts of CUDA and CUDNN. Please advise on what to do. I am very frustrated and nothing works.

I also used the OpenCL_SSE latest version too. That one uses just my CPU, not my GPU. Please advise on what to do.
I will be greatful

**Comment by TooMuchFun** [comment]
You do not have enough RAM to run the model. "OOM" means out of memory. You may try Quick96 but tbh but 4GB is not enough to use DFL well. Sorry.

**Comment by jiujitsu101** [comment]
My PC has 8 GB of RAM. The Graphics Card has memory of 4 GB. Actually, I found a way. I used the H128 trainer and with it 4/6 batch. That worked for me. And I got decent results.

**Comment by splinterz1** [comment]
![PreTrainBug](https://user-images.githubusercontent.com/58920647/71557407-a6ead180-2a3d-11ea-86e3-926b1ac98a07.png)

**Comment by wuffenberg** [comment]
Good. 
Then you should close the issue now.
