### ISSUE TITLE
Less vram available on RTX3080 after updating to latest version  

### ISSUE THREAD

**Issue by th14anon** [iperov/DeepFaceLab#5429]
After updating to the latest version of DFL, the available vram has dropped from 8.25gb to 7.27gb, resulting on oom errors on all my models. The only options i currently have is to reduce batch size to below 4 or disable models on gpu, neither is ideal. If no solution is available, would it be possible to re upload the version of dfl which has not got this issue?

**Comment by Cioscos** [comment]
It is not an issue. It is the free amount available for Tensorflow. Before DFL just showed total vram.

**Comment by th14anon** [comment]
Appreciate the response, but since updating from  a slightly older build i have been getting oom errors, and have had to reduce batch sizes  by quite a bit, I have also seen a few similar reports in the discord. It seems there have either been changes made to dfl which increase vram consumption or there is less vram available to dfl.

**Comment by Cioscos** [comment]
All people on Discord and here write this cause they don't know the fact I said.
Anyway which option did u activate?
Consider that adabelief optimizer consumes much more VRAM.

**Comment by th14anon** [comment]
i didn't change any model options, but have had to reduce batch sizes or disable models on gpu to prevent oom errors. Assuming no changes have been made to the dfl code, it seems that there is less vram available for it to use than there was previously.

**Comment by Cioscos** [comment]
The amount of vram showed changed since DFLab supports DirectX12 using tensorflow-directml. Ofc there was changes on code.
Assure to close every app which uses VRAM. I actually didn't recognize any sort of problem.
Are you sure the error is OOM from tensor allocation?

**Comment by th14anon** [comment]
Just some further information, after the following issue was resolved the issue began-https://github.com/iperov/DeepFaceLab/issues/5405

**Comment by th14anon** [comment]
Forgive my ignorance because i have limited knowledge on code, but is it possible the latest versions of cuda or tensorflow is leaving less vram for dfl to use on rtx3000 cards?

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
