### ISSUE TITLE
GPU not used on Mac

### ISSUE THREAD

**Issue by biogk** [iperov/DeepFaceLab#567]
## Expected behavior

I would expect using the AMD GPU to train the model.

##Actual behaviour

======= Model Summary ========
==                          ==
==        Model name: DF    ==
==                          ==
== Current iteration: 0     ==
==                          ==
==----- Model Options ------==
==                          ==
==       random_flip: True  ==
==        pixel_loss: False ==
==        batch_size: 2     ==
==                          ==
==------- Running On -------==
==                          ==
==      Using device: CPU   ==
==                          ==
==============================

The command:
python main.py train --training-data-src-dir extract --training-data-dst-dir extract1 --model-dir model --model DF

System: Mac OS Catalina

Python version: 3.6.10

**Comment by TooMuchFun** [comment]
> I would expect using the AMD GPU to train the model.

I wouldn't. 😂

**Comment by biogk** [comment]
> > I would expect using the AMD GPU to train the model.
> 
> I wouldn't. 😂

I switched to deepfakes/faceswap, and it worked.

**Comment by Lee-qian-gay** [comment]
You should use plaidml .
