### ISSUE TITLE
DeepFakeLab

### ISSUE THREAD

**Issue by EliasTegel** [iperov/DeepFaceLab#674]
Hi! 
Ive been trying to fix this problem that ive had for the past days, that ive been trying to solve.

The problem appears when I start training. A text saying: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.17G (2328711424 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory appears, even though I have the lowest settings. The strange thing is that I actually have a pretty decent gpu and cpu.

Specs: RTX 2070, I5-7600K 3.80GHz, 16GB ram.

**Comment by capsmanofficial** [comment]
Try that my friend:
==            resolution: 256                    ==
==             face_type: f                      ==
==     models_opt_on_gpu: True                   ==
==                 archi: df                     ==
==               ae_dims: 256                    ==
==                e_dims: 64                     ==
==                d_dims: 64                     ==
==           d_mask_dims: 22                     ==
==       masked_training: True                   ==
==             eyes_prio: False                  ==
==            lr_dropout: False                   ==
==           random_warp: True                  ==
==             gan_power: 0.0                    ==
==       true_face_power: 0.0                    ==
==      face_style_power: 0.0                    ==
==        bg_style_power: 0.0                    ==
==               ct_mode: none                   ==
==              clipgrad: False                  ==
==              pretrain: False                  ==
==       autobackup_hour: 0                      ==
== write_preview_history: False                  ==
==           target_iter: 0                      ==
==           random_flip: False                  ==
==            batch_size: 4

**Comment by TooMuchFun** [comment]
Lower resolution or reduce batch size.

**Comment by EliasTegel** [comment]
> Try that my friend:
> == resolution: 256 ==
> == face_type: f ==
> == models_opt_on_gpu: True ==
> == archi: df ==
> == ae_dims: 256 ==
> == e_dims: 64 ==
> == d_dims: 64 ==
> == d_mask_dims: 22 ==
> == masked_training: True ==
> == eyes_prio: False ==
> == lr_dropout: False ==
> == random_warp: True ==
> == gan_power: 0.0 ==
> == true_face_power: 0.0 ==
> == face_style_power: 0.0 ==
> == bg_style_power: 0.0 ==
> == ct_mode: none ==
> == clipgrad: False ==
> == pretrain: False ==
> == autobackup_hour: 0 ==
> == write_preview_history: False ==
> == target_iter: 0 ==
> == random_flip: False ==
> == batch_size: 4

It worked!! Thank you so much.

**Comment by aslan76** [comment]
From which file do we make these settings? 
I have that same problem

**Comment by AndrejHatzi** [comment]
Im having the same issue

**Comment by ghost** [comment]
Issue solved, please close it.
