### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by doopidydoopidy** [iperov/DeepFaceLab#762]
## Expected behavior

Trying to train and running out of memory? My system specifications should be able to handle a big batch size im not sure why not.

SPECS:

i7-6700K 4GHz
MSI RTX2070 SUPER 8GB
16BG RAM
Windows 10
Python v 3.7.6

## Actual behavior

**2020-05-28 09:48:35.966448: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory**

Initializing models: 100%|###############################################################| 5/5 [00:05<00:00,  1.05s/it]
Loading samples: 100%|############################################################| 2393/2393 [00:14<00:00, 161.66it/s]
Loading samples: 100%|##########################################################| 13542/13542 [00:50<00:00, 270.07it/s]
================== Model Summary ==================
==                                               ==
==            Model name: OP_SAEHD               ==
==                                               ==
==     Current iteration: 550224                 ==
==                                               ==
==---------------- Model Options ----------------==
==                                               ==
==            resolution: 128                    ==
==             face_type: wf                     ==
==     models_opt_on_gpu: True                   ==
==                 archi: df                     ==
==               ae_dims: 256                    ==
==                e_dims: 64                     ==
==                d_dims: 64                     ==
==           d_mask_dims: 22                     ==
==       masked_training: True                   ==
==             eyes_prio: False                  ==
==            lr_dropout: False                  ==
==           random_warp: True                   ==
==             gan_power: 0.0                    ==
==       true_face_power: 0.0                    ==
==      face_style_power: 0.0                    ==
==        bg_style_power: 0.0                    ==
==               ct_mode: none                   ==
==              clipgrad: False                  ==
==              pretrain: False                  ==
==       autobackup_hour: 0                      ==
== write_preview_history: False                  ==
==           target_iter: 0                      ==
==           random_flip: True                   ==
==            batch_size: 6                      ==
==                                               ==
==----------------- Running On ------------------==
==                                               ==
==          Device index: 0                      ==
==                  Name: GeForce RTX 2070 SUPER ==
==                  VRAM: 8.00GB                 ==
==                                               ==
===================================================
Starting. Press "Enter" to stop training and save model.
2020-05-28 09:48:35.966448: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-05-28 09:48:35.972989: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-05-28 09:48:36.092482: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-05-28 09:48:36.098304: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-05-28 09:48:36.126113: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-05-28 09:48:36.131332: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.14G (2297952256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[10:00:49][#552566][0252ms][0.2136][0.1062]

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by Vano333** [comment]
try training on packed src and dst aligned 

4.2) data_src util faceset pack.bat
5.2) data_dst util faceset pack.bat

**Comment by doopidydoopidy** [comment]
> 
> 
> try training on packed src and dst aligned
> 
> 4.2) data_src util faceset pack.bat
> 5.2) data_dst util faceset pack.bat

Didnt work unfortunately, same error. 
I actually have no idea what is wrong, everything is updated and I have decent specs..

**Comment by birdstream** [comment]
> Didnt work unfortunately, same error.
> I actually have no idea what is wrong, everything is updated and I have decent specs..

This may seem like a dumb answer, but have you tried to power off/on your computer?
I suppose you're on Windows, and i ran in to exactly the same issue on my Linux desktop after messing around with DFL. A full reboot solved the problem (NVIDIA driver issue maybe?)

**Comment by doopidydoopidy** [comment]
> 
> 
> > Didnt work unfortunately, same error.
> > I actually have no idea what is wrong, everything is updated and I have decent specs..
> 
> This may seem like a dumb answer, but have you tried to power off/on your computer?
> I suppose you're on Windows, and i ran in to exactly the same issue on my Linux desktop after messing around with DFL. A full reboot solved the problem (NVIDIA driver issue maybe?)
> 
> EDIT: Since Windows does some sort of hibernate when powering off, i suppose you should use "restart"

Tried, no difference. Could my actual Memory be busted? Brand new GFX card so it shouldnt be that.

**Comment by s1242001** [comment]
try
**[n] Place models and optimizer on GPU ( y/n ?:help ) : y**

I train on res128 df 256,64,64,16 bach 8 on a GTX1650 4G
with Place models and optimizer on GPU ( y/n ?:help ) : y

**Comment by birdstream** [comment]
> Tried, no difference. Could my actual Memory be busted? Brand new GFX card so it shouldnt be that.

Check if there are updated drivers for your card! What does nvidia-smi.exe say?
If memory serves me right (badum-tss!), there was actually a lot of people having memory issues with the RTX 20x0 cards that had to be returned.. But i certainly hope that that issue is resolved by now, since i'm planning for an upgrade myself (yeah, deepfaking on a GTX980 is kinda slow)

**Comment by Vano333** [comment]
try disable fast startup on win 10 and make normal reboot

https://www.computerhope.com/issues/ch001762.htm

**Comment by doopidydoopidy** [comment]
Clean reinstalled windows and deleted all partitions. works perfectly now, even at 12 batch size with no errors. Was annoying but glad it's solved. Im surprised DDU didnt fix it.

Cheers all
