### ISSUE TITLE
Error During SAEHD Training

### ISSUE THREAD

**Issue by Ingsten** [iperov/DeepFaceLab#802]
Hi there , i'm new with deepfacelab , and i got a problem everytime i try to train i got a lot of text error . What can it be?

`Error: OOM when allocating tensor with shape[8,128,130,130] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients/Conv2D_23_grad/Conv2DBackpropInput (defined at E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py:55) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'gradients/Conv2D_23_grad/Conv2DBackpropInput', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 456, in on_initialize
    gpu_G_loss_gvs += [ nn.gradients ( gpu_G_loss, self.src_dst_trainable_weights ) ]
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py", line 55, in tf_gradients
    grads = gradients.gradients(loss, vars, colocate_gradients_with_ops=True )
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 532, in _Conv2DGrad
    data_format=data_format),
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1307, in conv2d_backprop_input
    name=name)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'Conv2D_23', defined at:
  File "threading.py", line 884, in _bootstrap
[elided 3 identical lines from previous traceback]
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 330, in on_initialize
    gpu_pred_src_src, gpu_pred_src_srcm = self.decoder_src(gpu_src_code)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 113, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 148, in forward
    x = self.res2(x)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 113, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 70, in forward
    x = self.conv2(x)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\LayerBase.py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Conv2D.py", line 99, in forward
    x = tf.nn.conv2d(x, weight, self.strides, 'VALID', dilations=self.dilations, data_format=nn.data_format)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,128,130,130] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients/Conv2D_23_grad/Conv2DBackpropInput (defined at E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py:55) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,128,130,130] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node gradients/Conv2D_23_grad/Conv2DBackpropInput}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 123, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 453, in train_one_iter
    losses = self.onTrainOneIter()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 617, in onTrainOneIter
    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm_all, warped_dst, target_dst, target_dstm_all)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 488, in src_dst_train
    self.target_dstm_all:target_dstm_all,
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,128,130,130] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients/Conv2D_23_grad/Conv2DBackpropInput (defined at E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py:55) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'gradients/Conv2D_23_grad/Conv2DBackpropInput', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 456, in on_initialize
    gpu_G_loss_gvs += [ nn.gradients ( gpu_G_loss, self.src_dst_trainable_weights ) ]
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py", line 55, in tf_gradients
    grads = gradients.gradients(loss, vars, colocate_gradients_with_ops=True )
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 664, in gradients
    unconnected_gradients)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 420, in _MaybeCompile
    return grad_fn()  # Exit early
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 965, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 532, in _Conv2DGrad
    data_format=data_format),
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1307, in conv2d_backprop_input
    name=name)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'Conv2D_23', defined at:
  File "threading.py", line 884, in _bootstrap
[elided 3 identical lines from previous traceback]
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 330, in on_initialize
    gpu_pred_src_src, gpu_pred_src_srcm = self.decoder_src(gpu_src_code)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 113, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 148, in forward
    x = self.res2(x)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 113, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 70, in forward
    x = self.conv2(x)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\LayerBase.py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Conv2D.py", line 99, in forward
    x = tf.nn.conv2d(x, weight, self.strides, 'VALID', dilations=self.dilations, data_format=nn.data_format)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,128,130,130] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients/Conv2D_23_grad/Conv2DBackpropInput (defined at E:\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py:55) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.`

**Comment by Ingsten** [comment]
before i forget , my specs:

Intel i5 4460
16 Gb Ram
Geforce gtx 970

**Comment by test1230-lab** [comment]
OOM means out of memory. Lower your model parameters.

**Comment by developefake** [comment]
ı have 10 gb ram. what is the best parameter for my pc?

**Comment by developefake** [comment]
My other specs:
Amd Radeon phenom IIX 4 B965
 Gtx 1050ti 4 gb

**Comment by birdstream** [comment]
@developefake Your'e out of VRAM (graphics card). For SAEHD with 4GB VRAM, try something like this:
```
==--------- Model Options ----------==
==                                  ==
==            resolution: 128       ==
==             face_type: f         ==
==     models_opt_on_gpu: True      ==
==                 archi: liae      ==
==               ae_dims: 128       ==
==                e_dims: 80        ==
==                d_dims: 48        ==
==           d_mask_dims: 16        ==
==       masked_training: True      ==
==            learn_mask: True      ==
==             eyes_prio: False     ==
==            lr_dropout: n         ==
==           random_warp: True      ==
==             gan_power: 0.0       ==
==       true_face_power: 0.0       ==
==      face_style_power: 0.0       ==
==        bg_style_power: 0.0       ==
==               ct_mode: rct       ==
==              clipgrad: False     ==
==              pretrain: False     ==
==       autobackup_hour: 0         ==
== write_preview_history: False     ==
==           target_iter: 0         ==
==           random_flip: True      ==
==            batch_size: 8         ==
==           uniform_yaw: True      ==
```

You'd probably want to use the pretrained model found in the archives

**Comment by test1230-lab** [comment]
or the -ud archi

**Comment by varunpro** [comment]
I was getting similar errors ... what worked for me was going back to last Nvidia driver ... as I observed that these errors started after the latest nvidia driver update on 24.06 . See if that helps

**Comment by developefake** [comment]
> @developefake Your'e out of VRAM (graphics card). For SAEHD with 4GB VRAM, try something like this:
> 
> ```
> ==--------- Model Options ----------==
> ==                                  ==
> ==            resolution: 128       ==
> ==             face_type: f         ==
> ==     models_opt_on_gpu: True      ==
> ==                 archi: liae      ==
> ==               ae_dims: 128       ==
> ==                e_dims: 80        ==
> ==                d_dims: 48        ==
> ==           d_mask_dims: 16        ==
> ==       masked_training: True      ==
> ==            learn_mask: True      ==
> ==             eyes_prio: False     ==
> ==            lr_dropout: n         ==
> ==           random_warp: True      ==
> ==             gan_power: 0.0       ==
> ==       true_face_power: 0.0       ==
> ==      face_style_power: 0.0       ==
> ==        bg_style_power: 0.0       ==
> ==               ct_mode: rct       ==
> ==              clipgrad: False     ==
> ==              pretrain: False     ==
> ==       autobackup_hour: 0         ==
> == write_preview_history: False     ==
> ==           target_iter: 0         ==
> ==           random_flip: True      ==
> ==            batch_size: 8         ==
> ==           uniform_yaw: True      ==
> ```
> 
> You'd probably want to use the pretrained model found in the archives

So thanks! About pretrained model, to my heared it was at mr.deepfakes.com website. Can you acces it?

**Comment by birdstream** [comment]
@varunpro What was the version of the offending Nvidia driver?

**Comment by varunpro** [comment]
At my end, the model being trained was working ( training ) fine , after the update it started freezing and erroring, after the roll back to earlier nvidia driver, it started working like before. 

I believe 451.48-desktop-win10-64bit-international-dch-whql was the Nvidia update .

Though on a 4Gb vram card, the Dims and resolution should be low as mentioned above. So first ensure that ( as that's the most common cause of error )

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
