### ISSUE TITLE
OOM error while using similar gpu pretrained model

### ISSUE THREAD

**Issue by Mark-papi** [iperov/DeepFaceLab#955]
so im getting this error while im running my own pretrain model, is there any suggestion on what settings should i put, so i will not get the oom error, i know that this gpu is not good, it has 6gb vram but is there any setting that, will be good for results(quality) and also not prompt me with oom ?

i also tried a pretrained model of an other user but again i got the error, the thing is that the pretrained model was created with the 1060 6 gb which is way worse gpu than mine, and it has the same vram.

**this is the users one and bellow its mine** 
================= Model Summary =================
==                                             ==
==            Model name: 1_SAEHD              ==
==                                             ==
==     Current iteration: 750000               ==
==                                             ==
==--------------- Model Options ---------------==
==                                             ==
==            resolution: 256                  ==
==             face_type: wf                   ==
==     models_opt_on_gpu: True                 ==
==                 archi: df-ud                ==
==               ae_dims: 292                  ==
==                e_dims: 92                   ==
==                d_dims: 92                   ==
==           d_mask_dims: 16                   ==
==       masked_training: True                 ==
==             eyes_prio: False                ==
==           uniform_yaw: True                 ==
==            lr_dropout: n                    ==
==           random_warp: False                ==
==             gan_power: 0.0                  ==
==       true_face_power: 0.0                  ==
==      face_style_power: 0.0                  ==
==        bg_style_power: 0.0                  ==
==               ct_mode: none                 ==
==              clipgrad: False                ==
==              pretrain: True                 ==
==       autobackup_hour: 1                    ==
== write_preview_history: False                ==
==           target_iter: 750000               ==
==           random_flip: False                ==
==            batch_size: 7                    ==
==                                             ==
==---------------- Running On -----------------==
==                                             ==
==          Device index: 0                    ==
==                  Name: GeForce GTX 1060 6GB ==
==                  VRAM: 5.93GB               ==
==                                             ==
=================================================

**this is mine pretrained settings:**
================== Model Summary ==================
==                                               ==
==            Model name: train saehd_SAEHD      ==
==                                               ==
==     Current iteration: 0                      ==
==                                               ==
==---------------- Model Options ----------------==
==                                               ==
==            resolution: 224                    ==
==             face_type: wf                     ==
==     models_opt_on_gpu: True                   ==
==                 archi: df                     ==
==               ae_dims: 299                    ==
==                e_dims: 96                     ==
==                d_dims: 96                     ==
==           d_mask_dims: 22                     ==
==       masked_training: True                   ==
==             eyes_prio: False                  ==
==           uniform_yaw: True                   ==
==            lr_dropout: n                      ==
==           random_warp: False                  ==
==             gan_power: 0.0                    ==
==       true_face_power: 0.0                    ==
==      face_style_power: 0.0                    ==
==        bg_style_power: 0.0                    ==
==               ct_mode: none                   ==
==              clipgrad: False                  ==
==              pretrain: True                   ==
==       autobackup_hour: 0                      ==
== write_preview_history: False                  ==
==           target_iter: 0                      ==
==           random_flip: False                  ==
==            batch_size: 6                      ==
==                                               ==
==----------------- Running On ------------------==
==                                               ==
==          Device index: 0                      ==
==                  Name: GeForce GTX 1660 SUPER ==
==                  VRAM: 6.00GB                 ==
==                                               ==

thank you for any suggestion regarding my problem!

**Comment by Mark-papi** [comment]
ok i fixed it by creating more paging on my system, but it seems now i get this error 
2020-11-24 07:38:39.352338: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 481.91M (505321728 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
but the training works just fine.

**Comment by jiteshm17** [comment]
Maybe try reducing the batch size?

**Comment by ghost** [comment]
Did you ever find the answer?
