### ISSUE TITLE
nadagit/lbfs linux port not utilizing GPU

### ISSUE THREAD

**Issue by TheGermanEngie** [iperov/DeepFaceLab#966]
Been trying for days to try and get lbfs/DeepFaceLab_Linux to work. Mainly encountered user error programs but now when running ./4_data_src_extract_faces_S3FD.sh it only utilizes the CPU and my GPU (Tesla M40 24GB) sits at idle when opening nvidia-smi. Can someone tell me what I am doing wrong.

anaconda3 (deepfacelab) meta: 
nvidia-driver-455
python=3.6.8 
cudnn=7.6.5 
cudatoolkit=10.0.130

requirements-cuda.txt
-------------------------
tqdm
numpy==1.19.3
h5py
opencv-python==4.1.0.25
ffmpeg-python==0.1.17
scikit-image==0.14.2
colorama==0.4.4
tesnorflow-gpu==2.4.0rc1
pyqt5==5.15.2

^^^^^^^^^^^^^^^^^^^^ based on requirements-cuda.txt in https://libraries.io/github/iperov/DeepFaceLab

I have tried nagadit/DeepFaceLab_Linux as well with python==3.7 & cudatoolkit==10.1.243 but to no avail.

**Comment by eliliam** [comment]
I can second this, running the extract script prints out:
Running on CPU2
Running on CPU5
Running on CPU3
Running on CPU0
Running on CPU4
Running on CPU1

Even though nvidia-smi shows my 2080Ti

**Comment by TheGermanEngie** [comment]
> I can second this, running the extract script prints out:
> Running on CPU2
> Running on CPU5
> Running on CPU3
> Running on CPU0
> Running on CPU4
> Running on CPU1
> 
> Even though nvidia-smi shows my 2080Ti
> 
> Edit: I fixed the issue by rebooting, I'm guessing that sometime while my computer was on, I updated the nvidia drivers, which required a full reboot to become available to DFL.

Did updating the drivers to the latest version fix your issue? What driver did you update from?

**Comment by Joe-121** [comment]
@TheGermanEngie and anyone else struggling to install DFL Linux. I have managed to get DFL working on both Tesla T4, RTX 2080Ti and now one RTX 3090!
Sorry for the long post, but I thought some bit of what I have gone through might be useful in getting DFL to work on Linux. Has been a nightmare and I've spent days and days on it! But really happy that now got RTX 3090 working!

I will summarise a few lessons I learned for previous builds of DFL and RTX 2080, and then latest build DFL with RTX 3090:
**General things:**
-use ubuntu 20.04 if possible rather than earlier versions - seemed to have fewer problems with python paths and various other things.
-for cuda versions 10.1, make sure you install cudatoolkit using the conda installer, not "sudo apt install" since it is neater and less prone to path problems from within conda. (unless installing cudatoolkit 11.1 in which case you have to use "apt install" since conda has not yet released cudatoolkit 11.1, just 11.0 so far)
-make sure your nvidia driver matches your cuda version. Do not have multiple versions of nvidia driver and best not to have multiple cuda versions. Check nvidia driver is working by typing "nvidia-smi"
-Also, if having lots of cuda problems / GPU not working in DFL, check cuda from within the conda environment using a tool called Numba by typing:
conda install numba
numba -s
-A lot of problems with GPU not being recognised in DFL come from Tensorflow problems. If you want to test that Tensorflow is recognising your GPU, Also, to test Tensorflow, open python prompt by typing "python", then:
  >>>from tensorflow.python.client import device_lib
        >>>print(device_lib.list_local_devices())
This will output your GPU device details if all working correctly.

Nvidia website has all the info on which nvidia drivers work with which cuda toolkit:

https://docs.nvidia.com/deploy/cuda-compatibility/index.ht

Table 1. CUDA Toolkit and Compatible Driver Versions
CUDA Toolkit	Linux x86_64 Driver Version
CUDA 11.1 (11.1.0)	>= 450.80.02
CUDA 11.0 (11.0.3)	>= 450.36.06
CUDA 10.2 (10.2.89)	>= 440.33
CUDA 10.1 (10.1.105)	>= 418.39
CUDA 10.0 (10.0.130)	>= 410.48
CUDA 9.2 (9.2.88)	>= 396.26
CUDA 9.1 (9.1.85)	>= 390.46
CUDA 9.0 (9.0.76)	>= 384.81
CUDA 8.0 (8.0.61 GA2)	>= 375.26
CUDA 8.0 (8.0.44)	>= 367.48
CUDA 7.5 (7.5.16)	>= 352.31
CUDA 7.0 (7.0.28)	>= 346.46

Using DFL early Dec build which did NOT yet use tensorflow 2.4, I found that the following worked. This guide will NOT work for latest build but I include it here in case anyone using old builds from 1 month+ ago using tensorflow 2.3 and earlier:

Make sure you are NOT logged in as root, but instead as a user with sudo privileges. If you are logged in as root, the paths in the env.sh file do not work.

Install Anaconda by doing:
sudo apt-get install wget
sudo wget https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
bash Anaconda3-2020.11-Linux-x86_64.sh 

Anaconda should automatically add the PATH if you say yes to the question/prompt about "conda init" but to be on the safe side, after install you can enter:
export PATH=~/anaconda3/bin:$PATH
conda init bash

Then set up conda environment and the dependencies within conda:
conda create -n deepfacelab -c main python=3.8 cudnn=7.6.5 cudatoolkit=10.1.243  [or you can use python=3.7]
 conda activate deepfacelab
 git clone --depth 1 https://github.com/nagadit/DeepFaceLab_Linux.git
 cd DeepFaceLab_Linux
 git clone --depth 1 https://github.com/iperov/DeepFaceLab.git

Then edit the requirements-cuda file to change to:
numpy==1.18.0
h5py==2.10.0
opencv-python==4.1.0.25
ffmpeg-python==0.1.17
scikit-image==0.14.2
scipy==1.4.1
colorama==0.4.4
tensorflow-gpu==2.3.1
pyqt5==5.15.2
(if I did not specify a version for pyqt5 or colorama, conda packages install failed on some versions of ubuntu. Version of h5py needed to be slightly newer than in the standard txt file)

Then finish with:
python -m pip install -r ./DeepFaceLab/requirements-cuda.txt
Make sure you still install these from within the deepfacelab conda environment.

If there seem to be problems between tensorflow and cuda, (GPU card not recognised in Training) then try this:
remove the "conda create" entries above for cudnn and cudatoolkit and just creat the conda environment with python 3.7 or 3.8. Then when it comes to install the stuff in the requirements-cuda.txt, you can use either tensorflow-gpu==2.3.1 or just "tensorflow-gpu", and the tensorflow package installer examined my system and installed the latest tensorflow (2.3 I think it was) and since I did not have cuda installed yet, it also automatically installed the correct cudatoolkit (and cudnn I think). Tensorflow 2.4.0 does NOT yet include cudatoolkit, so it will not auto-install cudatoolkit if it is missing. Remember, Tensorflow 2.4.0 requires cuda 11 or higher.

If DFL throws an error that one of the above modules in requirements.txt is missing, try install from CLI using the conda isntall command:
e.g. conda install ffmpeg-python

The linux env.sh file used to be wrong for the python version, since it specifies 3.6. Unless you have downloaded the latest files from Nagadit, if using older ones, you need to edit the env.sh file to change this to 3.7 or just "python3" (but not 3.6 since this usually throws an error that 3.6 not found), then save. If you install fresh today, this has now been fixed. 

Also in the env.sh file: 
on some versions of Ubuntu (not others which were ok for some reason), I had to specify the path to the folders, so for instance: 

Instead of:
export DFL_ROOT="./"
export DFL_SRC="./DeepFaceLab"

you may need to change to the full path which would be something like: 
export DFL_ROOT="/home/YOUR-USERNAME/DeepFaceLab_Linux/"
export DFL_SRC="/home/YOUR-USERNAME/DeepFaceLab_Linux/DeepFaceLab"

Put whatever your linux username is in there instead of YOUR-USERNAME.
I had to do this to get DFL working on ubuntu 20.04 via virtual machine on RTX 3090 with latest iperov builds. Don't know why!

**Now, importantly moving on to the latest DFL version with RTX 3000 cards:**
I have also eventually got DFL to work including training SAEHD and XSeg.
Use above method but change the conda create step to:
conda create -n deepfacelab -c main python=3.8 (remove cudnn and cudatoolkit entries)
Change requirements cuda.txt file to include 
tensorflow-gpu 2.4.0

Go to Nvidia website and download+install cudnn 8.0.5 (you will have to register for an nvidia account - easy. Use the cudnn version for cuda 11.1).
Then install cudatoolkit 11.1 as per website https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html  
For my install on ubuntu 20.04, it was:
wget -O /etc/apt/preferences.d/cuda-repository-pin-600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt install cuda-toolkit-11-1
export PATH=/usr/local/cuda-11.1/bin${PATH:+:${PATH}}

DFL should then work on RTX 3090.
However, I had an older CPU (Xeon E5-2680) and despite having 16 cores, it could not run DFL. When trying to run training, it would fail at the last line in the DFL script. It would say "illegal instruction, core dumped". I found this was due to Tensorflow again. Despite tensorflow 2.4.0 recognising the RTX 3090 (test using the script above), it could not train. This was because Tensorflow checks that the CPU can support AVX or AVX2. Tensorflow 2.3 supports both. Tensorflow 2.4.0 only supports CPUs with AVX2. This was by accident by the staff at Tensorflow. I had to remove tensorflow 2.4.0 and compile my own tensorflow 2.5.0. This worked a charm and I can now train SAEHD and XSeg on the RTX 3090 at good speeds!
If you need to compile your own tensorflow that is specific to your own machine, follow this link below. It is not too hard but you will need to leave your computer for a few hours to compile.
https://www.tensorflow.org/install/source

You should install Bazelisk to help the tensorflow compiling:
$ wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64
$ chmod +x bazelisk-linux-amd64
$ sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
$ bazel version

I will post this fix for the CPU and DFL on its own too.

Hope all this helps someone out there!
Joe

**Comment by GraysonChang** [comment]
Finally, I can use my GPU... My CUDA is 10.1, CUDNN 7.6, and I change the `tensorflow-gpu==2.4.0` to `tensorflow-gpu==2.3.1` in the requirements.txt. The GPU is work!!! Thanks to @Joe-121

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
